# Generated by Django 4.0.5 on 2022-07-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_adress_zip'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')
        """, """
            DELETE FROM store_collection
            WHERE title='collection1'
        """)
    ]
